#!/usr/bin/with-contenv sh

exec /usr/libexec/mysqld \
  --basedir=/usr \
  --datadir=/var/lib/mysql \
  --plugin-dir=/usr/lib/mysql/plugin \
  --user=mysql \
  --open-files-limit=65534 \
  --socket=/var/lib/mysql/mysql.sock 2>&1 >/dev/stderr
