#!/usr/bin/with-contenv sh

create_mysql_admin_user() {
  NEED_MYSQL=1
  if pgrep mysqld > /dev/null; then
    NEED_MYSQL=0
  fi

  if [ $NEED_MYSQL -ne 0 ]; then
    /usr/bin/mysqld_safe --user=mysql > /dev/null 2>&1 &

    RET=1
    while [[ $RET -ne 0 ]]; do
      echo "=> Waiting for confirmation of MySQL service startup"
      sleep 5
      mysql -uroot -e "status" > /dev/null 2>&1
      RET=$?
    done
  fi

  PASS=$MYSQL_PASS
  _word=$( [ $MYSQL_PASS ] && echo "preset" || echo "random" )
  echo "=> Creating MySQL admin user with ${_word} password"

  mysql -uroot -e "CREATE USER 'admin'@'%' IDENTIFIED BY '$PASS'"
  mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION"
  mysql -uroot -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY '$PASS'"
  mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' WITH GRANT OPTION"

  # Remove anonymous users without a password. Remove remote root (with no password.)
  mysql -uroot -e "DROP USER ''@'`hostname`'"
  mysql -uroot -e "DROP USER 'root'@'`hostname`'"
  mysql -uroot -e "DROP USER ''@'localhost'"
  mysql -uroot -e "FLUSH PRIVILEGES;"

  echo "=> Done!"

  echo "=> ===================================================================="
  echo "=> You can now connect to this MySQL Server using:"
  echo "=>"
  echo "=>    mysql -uadmin -p$PASS -h<host> -P<port>"
  echo "=>"
  echo "=> Please remember to change the above password as soon as possible!"
  echo "=> MySQL user 'root' has no password but only allows local connections."
  echo "=> ===================================================================="

  if [ $NEED_MYSQL -ne 0 ]; then
    mysqladmin -uroot shutdown
  fi
}

VOLUME_HOME="/var/lib/mysql"

if [[ ! -d $VOLUME_HOME/mysql ]]; then
  echo "=> An empty or uninitialized MySQL volume is detected in $VOLUME_HOME"
  echo "=> Installing MySQL ..."
  mysql_install_db --user=mysql > /dev/null 2>&1
  echo "=> Done!"
  create_mysql_admin_user
else
  echo "=> Using an existing volume of MySQL"
fi

echo "WAT"

exec /usr/libexec/mysqld \
  --basedir=/usr \
  --datadir=/var/lib/mysql \
  --plugin-dir=/usr/lib/mysql/plugin \
  --user=mysql \
  --open-files-limit=65534 \
  --socket=/var/lib/mysql/mysql.sock 2>&1 >/dev/stderr

